/*

responsive.js

Shared JavaScript functions

For all code in the WebEdit object:

(C) 2019 Spoton.net Limited - http://spoton.net/

All other code was written by Kate Morley independently from her employment at
Spoton.net Limited, and she retains copyright. The code is available from
http://code.iamkate.com/ and is released under the terms of the CC0 1.0
Universal legal code:

http://creativecommons.org/publicdomain/zero/1.0/legalcode

*/

runOnLoad(function(){return document.documentElement.classList.add("wScripts")});
W.Animation=function(){var c=window.requestAnimationFrame||function(a){return window.setTimeout(a,16)};return{call:c,throttle:function(a){var b=!1;return function(){b||(b=!0,c(function(){a();b=!1}))}}}}();
W.Background=function(){function n(b){b.forEach(function(a){h.get(a.target).visible=a.isIntersecting;k(a.target)})}function p(b){var a=b.parentNode,f={visible:!l,active:!0,width:null,height:null},c;for(c in b.dataset)"background"===c.substring(0,10)&&(f[c.substring(10)]=b.dataset[c]);q&&(f.Attachment="scroll");h.set(a,f);l?l.observe(a):k(a);f.Prefix&&"parallax"===f.Attachment&&(0===m.length&&window.addEventListener("scroll",function(){return m.forEach(k)}),m.push(a));a.classList.add("w-text-"+(.5>f.Luminance?"light":"dark"))}function r(){h.forEach(function(b,a){return k(a)})}function k(b){var a=h.get(b);if(a.visible&&a.active){var f=b.getBoundingClientRect(),c=f.width,d=f.height,g=window.innerWidth,e=window.innerHeight;"fixed"===a.Attachment&&(c=g,d=e);"parallax"===a.Attachment&&(c=g,d=(d+e)/2);if(a.width!==c||a.height!==d||"parallax"===a.Attachment)a.width=c,a.height=d,c=[],a.OverlayColour&&c.push("linear-gradient("+a.OverlayColour+","+a.OverlayColour+")"),a.Prefix?c.push(t(a,f,e)):c.push("#000"),b.style.background=c.join(",")}}function t(b,a,f){var c=b.AspectRatio/(b.width/b.height),d=4<c?3:2<c?2:c>4/3?1:1<=c?0:.25>c?7:.5>c?6:.75>c?5:4,g=b.Position,e=1;if("parallax"===b.Attachment){g=g.split(" ");if(4>d)e=0;else{e=b.AspectRatio;switch(d){case 5:e*=4/3;break;case 6:e*=2;break;case 7:e*=4}e=b.width/e-b.height}e=(a.top+(a.height-f)/2)/2-e*(parseInt(g[1])/100-.5);g=g[0]+" calc(50% + "+Math.floor(e)+"px)";e=b.height/f}f='url("'+W.ROOT_PATH+"_webedit/cached-images/"+b.Prefix+d;d=4>d?b.height:b.width;d*=window.devicePixelRatio;if(3072<=d)d="p";else{a=0;for(var h=16;d>1.5*h;)a+=2,h*=2;d=d<=h?String.fromCharCode(a+97):String.fromCharCode(a+98)}g=f+d+"."+b.Extension+'") '+g+"/";c=1<=c?"auto "+Math.ceil(100*e)+"%":"100% auto";return g+c+" no-repeat"+("scroll"===b.Attachment?"":" fixed")}var q=matchMedia("(hover:none)").matches,l=window.IntersectionObserver?new IntersectionObserver(n,{rootMargin:"500px"}):null,h=new Map,m=[];runOnLoad(function(){[].forEach.call(document.querySelectorAll("[data-background-luminance]"),p);W.Message.subscribe("layout",r)});return{}}();
W.Message=function(){function e(a,b){c[a].forEach(function(a){return a(b)})}var c={};return{publish:function(a,b,d){a in c&&(d?e(a,b):window.setTimeout(function(){return e(a,b)},0))},subscribe:function(a,b){a in c?c[a].push(b):c[a]=[b];var d=c[a].length-1;return function(){delete c[a][d]}}}}();
W.Modal=function(){function a(a,b){""!==d.className?f=[a,b]:(d.className="w-modal-show","string"===typeof a?g.textContent=a:(g.textContent="",g.appendChild(a)),h.textContent="",b||(b=[{label:"Close",listener:e}]),b.forEach(function(a){return h.appendChild(c(a))}))}function c(a){var b=k.cloneNode(!0);b.lastChild.textContent=a.label;b.addEventListener("click",a.listener);return b}function e(){d.className="w-modal-hide";window.setTimeout(function(){d.className="";f&&(a.apply(null,f),f=null)},200)}var d,g,h,k,f=null;runOnLoad(function(){d=document.getElementById("w-modal");var a=d.lastChild;g=a.firstChild;h=a.lastChild;k=h.lastChild});return{show:a,showError:function(c,b){b=void 0===b?[]:b;var d=document.createElement("div");d.className="w-modal-error";d.textContent=c;if(0<b.length){var e=document.createElement("ul");b.forEach(function(a){var b=document.createElement("li");b.textContent=a;e.appendChild(b)});d.appendChild(e)}a(d)},hide:e}}();
W.Scroller=function(){function h(a){for(var b=a.target;b&&"A"!==b.nodeName;)b=b.parentNode;b&&(b=b.getAttribute("href"),"#"!==b&&"#"===b.substring(0,1)&&(a.preventDefault(),history.pushState(null,null,b),(a=document.getElementById(b.substring(1)))?f(a.getBoundingClientRect().top):f(0)))}function f(e){c=Math.round(window.pageYOffset);d=Math.max(0,Math.round(e)+c-W.Sticky.getOffset());a=0;g()}function g(){0>a?d>c-e(-a)?a++:d<=c-e(1-a)&&a--:d<c+e(a)?a--:d>=c+e(a+1)&&a++;c+=a;window.scrollTo(0,c);c!==d&&window.requestAnimationFrame(g)}function e(a){return a*(a+1)/2}var c=0,a=0,d=0;runOnLoad(function(){return document.body.addEventListener("click",h)});return{scrollTo:f}}();
W.Sticky=function(){function e(){c.filter(function(a){return!a.fixed}).forEach(function(a){a.node.style.minHeight=a.child.clientHeight+"px"});f()}function f(){c.filter(function(a){return!a.fixed}).forEach(function(a){var b=Math.ceil(a.node.getBoundingClientRect().top)<a.top;a.node.classList[b?"add":"remove"]("w-sticky-fixed")})}function g(){if(0===c.length)return 0;var a=d();return Math.max.apply(Math,c.map(function(b){return-1<b.at.indexOf(a)?b.child.clientHeight+b.top:0}))}function d(){for(var a in W.BREAKPOINTS.MATCHERS)if(W.BREAKPOINTS.MATCHERS[a].matches)return a}var c=[];W.EDIT_MODE||runOnLoad(function(){c=[].map.call(document.querySelectorAll(".w-sticky"),function(a){return{node:a,child:a.children[0],fixed:a.classList.contains("w-sticky-fixed"),at:a.dataset.stickyAt.split(" "),top:+a.dataset.stickyTop}});e();window.addEventListener("resize",e);window.addEventListener("scroll",f);if(location.hash){var a=document.getElementById(location.hash.substr(1));if(a){var b=g(),d=parseInt(window.getComputedStyle(a).marginTop);a.setAttribute("style","margin-top:"+-b+"px !important");a.style.paddingTop=b+d+"px"}}});return{getOffset:g}}();
(function(){function c(b,a){return function(d){d=b.replace("[",encodeURIComponent(location.href)).replace("]",encodeURIComponent(document.title));a?window.open(d,"_blank","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,width=500,height="+a):location.href=d}}function e(b){return function(){var a=b.parentNode.parentNode.querySelector(".wSharePanel");a.style.display="block"===a.style.display?"none":"block"}}var f=[c("mailto:?body=[&subject=]"),c("https://twitter.com/intent/tweet?url=[&text=]",450),c("https://www.facebook.com/sharer.php?u=[",330),c("https://www.linkedin.com/shareArticle?mini=true&url=[",520)];runOnLoad(function(){for(var b=document.querySelectorAll(".wShare button"),a=0;a<b.length;a++)b[a].addEventListener("click",e(b[a]));b=document.querySelectorAll(".wShareIcons");for(a=0;a<b.length;a++)for(var d=b[a],c=0;c<d.children.length;c++)d.children[c].addEventListener("click",f[c])})})();
(function(){function c(){if(!a||W.EDIT_MODE)a=document.querySelectorAll("[data-webedit-scale]");for(var b=0;b<a.length;b++)a[b].style.fontSize=a[b].offsetWidth/a[b].getAttribute("data-webedit-scale")+"em"}var a;runOnLoad(c);W.Message.subscribe("layout",c)})();
(function(){function l(){f=[];for(var c={},a=document.getElementsByClassName("wSpacer"),e=0;e<a.length;e++){for(var d=a[e],b=d.parentNode;b&&(!/wSplit/.test(b.className)||4>b.childNodes.length);)d=b,b=b.parentNode;if(b){var b=b.getBoundingClientRect(),b=b.top+"-"+b.left,g=d.getBoundingClientRect(),g=g.top+"-"+g.left;c[b]||(c[b]={});c[b][g]||(c[b][g]=[]);c[b][g].push([a[e],d])}}for(var h in c){a=[];for(d in c[h])for(e=0;e<c[h][d].length;e++)a.length<=e&&a.push([e,[]]),a[e][1].push(c[h][d][e]);f=f.concat(a)}}function m(){for(var c=document.getElementsByClassName("wSpacer"),a=0;a<c.length;a++)c[a].style.height=0;c=document.querySelectorAll("[data-aspect-ratio]");for(a=0;a<c.length;a++)0<c[a].offsetWidth&&(c[a].style.height=Math.round(c[a].offsetWidth*parseFloat(c[a].getAttribute("data-aspect-ratio")))+"px");c=[];for(a=0;a<f.length;a++){for(var e={},d=0;d<f[a][1].length;d++){var b=f[a][1][d][1].getBoundingClientRect().top;e[b]||(e[b]=[]);e[b].push(f[a][1][d][0])}for(b in e)c.push([parseInt(b),f[a][0],e[b]])}c.sort(function(a,b){var c=a[0]===b[0]?1:0;return a[c]<b[c]?-1:1});for(a=0;a<c.length;a++){b=[];for(d=0;d<c[a][2].length;d++)b.push(c[a][2][d].getBoundingClientRect().top);e=Math.max.apply(Math,b);for(d=0;d<c[a][2].length;d++)c[a][2][d].style.height=Math.round(e-b[d])+"px"}}var f;if(!W.EDIT_MODE){if(window.matchMedia)for(var k=0;k<W.BREAKPOINTS.BOUNDARIES.length;k++)matchMedia("(max-width:"+W.BREAKPOINTS.BOUNDARIES[k]+"px)").addListener(l);runOnLoad(function(){l();m();W.Message.subscribe("layout",m)})}})();
runOnLoad(function(){for(var b=document.getElementsByTagName("iframe"),a=0;a<b.length;a++){var c=b[a].getAttribute("data-webedit-scrolling");c&&b[a].setAttribute("scrolling",c)}});
runOnLoad(function(){function c(a){var d=function(){return a.style.opacity=1};window.setTimeout(d,5E3);a.addEventListener("load",d);a.src=a.getAttribute("data-src")}var e=document.querySelectorAll("iframe[data-src]");if(window.IntersectionObserver){var b=new IntersectionObserver(function(a){a.forEach(function(a){a.isIntersecting&&(b.unobserve(a.target),c(a.target))})},{rootMargin:"500px"});[].forEach.call(e,b.observe.bind(b))}else[].forEach.call(e,c)});
runOnLoad(function(){publish=W.Animation.throttle(function(){return W.Message.publish("layout",null,!0)});window.addEventListener("load",publish);window.addEventListener("resize",publish);[].forEach.call(document.querySelectorAll(".wShowHide > input"),function(a){return a.addEventListener("change",publish)})});
runOnLoad(function(){for(var d=document.getElementsByTagName("table"),c=0;c<d.length;c++){var b=d[c].getElementsByTagName("th");if(0<b.length){for(var e=[],a=0;a<b.length;a++)e[a]=b[a].textContent;b=d[c].tBodies[0].getElementsByTagName("td");for(a=0;a<b.length;a++)e[b[a].cellIndex]&&b[a].setAttribute("data-table-header",e[b[a].cellIndex])}}});
runOnLoad(function(){if(document.querySelector(".pswp")){var a=document.createElement("script");a.src=W.ROOT_PATH+"_webedit/generator/lightbox/lightbox.js";document.body.appendChild(a)}});
runOnLoad(function(){function b(a){a.target.parentNode.parentNode.classList.toggle("wMenuOpen")}window.setTimeout(function(){return document.documentElement.classList.add("wMenu")},0);[].forEach.call(document.querySelectorAll(".wMenuNavigation"),function(a){a.onclick=b})});

// http://code.iamkate.com/javascript/touch-friendly-drop-down-menus/
(function(){function f(){return"none"!=window.getComputedStyle(document.getElementById("wMenuIcon")).display}function h(a){if(!f()){for(var b=!1,d=0;d<e.length;d++)e[d].isOpen&&(b=!0);if(b){for(a=a.target;null!=a;){if(/\bwDropdown\b/.test(a.className))return;a=a.parentNode}g()}}}function g(a){for(var b=0;b<e.length;b++)e[b]!=a&&e[b].close()}function c(a){this.node=a;a.className+=" wDropdownJavaScript";a.addEventListener("mouseover",this.bind(this.handleMouseOver));a.addEventListener("mouseout",this.bind(this.handleMouseOut));a.addEventListener("click",this.bind(this.handleClick));a.addEventListener("touchstart",this.bind(this.handleClick))}var e=[];c.prototype.isOpen=!1;c.prototype.timeout=null;c.prototype.bind=function(a){var b=this;return function(){a.apply(b,arguments)}};c.prototype.handleMouseOver=function(a,b){this.clearTimeout();var d="target"in a?a.target:a.srcElement;for(;"LI"!=d.nodeName&&d!=this.node;)d=d.parentNode;"LI"==d.nodeName&&(this.toOpen=d,this.timeout=window.setTimeout(this.bind(this.open),b?0:250))};c.prototype.handleMouseOut=function(){this.clearTimeout();this.timeout=window.setTimeout(this.bind(this.close),250)};c.prototype.handleClick=function(a){if(!f()){g(this);var b="target"in a?a.target:a.srcElement;for(;"LI"!=b.nodeName&&b!=this.node;)b=b.parentNode;"LI"==b.nodeName&&0<this.getChildrenByTagName(b,"UL").length&&!/\bwDropdownOpen\b/.test(b.className)&&(this.handleMouseOver(a,!0),a.preventDefault())}};c.prototype.clearTimeout=function(){this.timeout&&(window.clearTimeout(this.timeout),this.timeout=null)};c.prototype.open=function(){this.isOpen=!0;for(var a=this.getChildrenByTagName(this.toOpen.parentNode,"LI"),b=0;b<a.length;b++){var d=this.getChildrenByTagName(a[b],"UL");if(0<d.length)if(a[b]!=this.toOpen)a[b].className=a[b].className.replace(/\bwDropdownOpen\b/g,""),this.close(a[b]);else if(!/\bwDropdownOpen\b/.test(a[b].className)){a[b].className+=" wDropdownOpen";for(var c=0,e=d[0];e;)c+=e.offsetLeft,e=e.offsetParent;right=c+d[0].offsetWidth;0>c&&(a[b].className+=" wDropdownLeftToRight");right>document.body.clientWidth&&(a[b].className+=" wDropdownRightToLeft")}}};c.prototype.close=function(a){a||(this.isOpen=!1,a=this.node);a=a.getElementsByTagName("li");for(var b=0;b<a.length;b++)a[b].className=a[b].className.replace(/\bwDropdownOpen\b/g,"")};c.prototype.getChildrenByTagName=function(a,b){for(var d=[],c=0;c<a.childNodes.length;c++)a.childNodes[c].nodeName==b&&d.push(a.childNodes[c]);return d};runOnLoad(function(){document.body.addEventListener("touchstart",h,!1);for(var a=document.querySelectorAll("ul.wDropdown"),b=0;b<a.length;b++)e.push(new c(a[b]))})})();
